### ISSUE TITLE
:shield: Protéger data avec la CI

### ISSUE THREAD

**Issue by adriens** [opt-nc/odata-domaines-marques-opt-nc#1]
# :dart: Objectif

Protéger les données avec ces contraintes:

- 'domain`: 'VARCHAR' NOT NULL,
- `marque_nom`: 'VARCHAR NOT NULL, UNIQUE',
- `marque_description`: 'VARCHAR' NOT NULL, UNIQUE,
- `url`: 'VARCHAR'

# :information_source: Ressources

Exemple de load sql : 

```python
df = con.query("""FROM read_csv('https://raw.githubusercontent.com/opt-nc/odata-domaines-marques-opt-nc/main/data/domaines.csv',
    delim = ',',
    header = true,
    columns = {
        'domain': 'VARCHAR',
        'marque_nom': 'VARCHAR',
        'marque_description': 'VARCHAR',
        'url': 'VARCHAR'
    });""").to_df()
df
```

# :bookmark: Liens

[DOMAINE.nc reporting for dummies](https://www.kaggle.com/code/adriensales/domaine-nc-reporting-for-dummies#%F0%9F%A4%94-Domaines-et-impact-sur-les-marques)

![image](https://github.com/opt-nc/odata-domaines-marques-opt-nc/assets/5235127/75499cf2-cac1-403c-87c1-cea7110c8fe8)
![image](https://github.com/opt-nc/odata-domaines-marques-opt-nc/assets/5235127/1be85cc1-c930-470e-b2ba-c06f0613576b)

**Comment by mbarre** [comment]
@adriens , il n'y aura que ce fichier sur la repo ou d'autres vont arriver ?

**Comment by adriens** [comment]
Non, y'en a qu'un. pourquoi, si jamais un jour y'en a plus ça crée un souci ?

**Comment by mbarre** [comment]
non, c'est juste pour savoir si je fais un dossier sql pour recevoir plusieurs script de check (comme pour la carto). Ou si je fais un seul fichier sql a la racine

**Comment by adriens** [comment]
LOL sinon, tu fais tout en python, mais ouep, sinon ton approche est top

**Comment by mbarre** [comment]
~~un branche develop ou c'est pas la peine~~

**Comment by adriens** [comment]
Top comme boulot @mbarre 👍 😎
